- name: Provision GCP instance
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Add user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reboot the VM to apply group changes
      ansible.builtin.reboot:

    - name: Wait for the VM to become available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    # - name: Copy files and folder to the VM
    #   ansible.builtin.copy:
    #     src: ../fabric
    #     dest: 
    #     remote_src: yes

    # - name: Copy the "fabric" folder to the VM
    #   ansible.builtin.copy:
    #     src: /path/to/your/fabric-folder
    #     dest: /path/on/remote/vm/
    #     remote_src: yes